### ISSUE TITLE
Make p+epsilon bribe contract

### ISSUE THREAD

**Issue by whwgeorge** [kleros/kleros-attacks#5]
Make contract of p+epsilon attack following description of https://blog.ethereum.org/2015/01/28/p-epsilon-attack/

Roughly:

Inputs : contract address and disputeID on which to perform bribe, desired outcome (denote by Y, denote the othe outcome by X), epsilon

After all appeals are resolved and outcome of dispute is finalized : 
If Y wins dispute
       Return balance of account to attacker

If X wins dispute
1)  Determine payout to coherent jurors p 
2) Pay each juror who voted Y d+p+epsilon (so that after their lost deposit of d, they obtain epsilon more than what the coherent jurors who voted X received).
3) Return balance of contract to attacker

**Comment by dannybabbev** [comment]
I will provide the implementation of this shortly.

However, a few notes on my side:
- This attack works as written if the votes submitted by the jurors are not visible until the end of the dispute.
- In the particular case of Kleros, everyone knows the exact number of jurors and how they voted, immediately after the vote is submitted. That means that right after half - 1 of the jurors have cast their votes for the attacker , everyone else knows that if they vote for the attacker, they get 0. This changes the payout matrix and now everyone would vote honestly again.

**Comment by clesaege** [comment]
In the image, link to a forum post about the attack.

**Comment by dannybabbev** [comment]
This can be closed @clesaege
